### PR TITLE
declaring your_character variable

### PR DESCRIPTION
**Pull request by Gerson2102**
I just added the variable in the cairo program.

## Checklist
- [#634 ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by edg-l** [comment]
you should also uncomment the test case so its actually checked now

**Review by juanbono — CHANGES_REQUESTED** [review]
Check that the test is not passing.

**Comment by Gerson2102** [comment]
> Check that the test is not passing.

I dont get it. I just declared a variable, but i did not run anything because that was the problem. That the variable was not declared. And i saw that the CI was failing...

**Comment by Gerson2102** [comment]
And i have the project like this:

image

Is like, is not recognizing my cairo language, and i dont know why.

**Pull request closed without merging**
