### PR TITLE
Update some crate versions

### PR DESCRIPTION
**Pull request by tcoratger**
## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by juanbono — DISMISSED** [review]

**Comment by edg-l** [comment]
please resolve the conflicts

**Comment by tcoratger** [comment]
> please resolve the conflicts

@edg-l done

**Review by edg-l — DISMISSED** [review]

**Review by juanbono — APPROVED** [review]

**Comment by juanbono** [comment]
@tcoratger please, fix conflicts :)

**Comment by tcoratger** [comment]
> @tcoratger please, fix conflicts :)

done

**Review by edg-l — DISMISSED** [review]

**Review by azteca1998 — DISMISSED** [review]

**Review by juanbono — CHANGES_REQUESTED** [review]
I think we can wait for upgrading dependencies since the code is moving a lot.

**Comment by igaray** [comment]
Hi @tcoratger Thanks for updating it, but allthough most of the updates are minor patches, I'd like to hold of on merging this for the time, until we stabilize some of the other changes we're working on.

**Comment by tcoratger** [comment]
@igaray Since https://github.com/lambdaclass/cairo_native/pull/566 is merged, we could merge this one, wdyt?

**Comment by tcoratger** [comment]
@pefontana I know that this is a stupid small PR but I would not close it for two reasons:
- It contains the update of all the crates. Even if there are no breaking changes, for example the version `0.2` currently used for num-traits dates from 6 years ago while `0.2.19` dates from 2 months ago . I think we can expect some small bug fixes or performance improvements in this time frame. I have the impression that it's the same reasoning for others.
- Also I did a `cargo update` which updated and cleaned the `Cargo.lock` a little, which is still not bad :)

What do you think? Feel free to keep it close, but it seems just to me a small improvement of the project.

**Pull request closed without merging**
