### PR TITLE
Refactor `sint8` to use `BlockExt` trait

### PR DESCRIPTION
**Pull request by RajeshRk18**
## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by edg-l — DISMISSED** [review]

**Comment by edg-l** [comment]
Thanks for you contribution!

Looks like clippy is complaining

**Review by igaray — APPROVED** [review]

**Review by igaray — CHANGES_REQUESTED** [review]
Hi @RajeshRk18 ! The tests are failing but as @edg-l said it looks good. If you can fix the CI pass we'll take another look.

**Comment by RajeshRk18** [comment]
Ready for review now @igaray @edg-l

**Review by azteca1998 — APPROVED** [review]

**Comment by edg-l** [comment]
has conflicts

**Comment by edg-l** [comment]
Closing as the author hasnt fixed the conflicts

**Pull request closed without merging**
