### PR TITLE
adding helper to debug_print()

### PR DESCRIPTION
**Pull request by Gerson2102**
## Checklist
- [ #543] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by Gerson2102** [comment]
It seems that the `rust_analyzer` extension is not working for me in those files inside of metadata directory. In `debug_utils.rs` was the only file where i found the problems related to the issue.

**Comment by Gerson2102** [comment]
I was searching if that function is used in the project, and i did not find it. That was the reason that i did not change the parameters in other calls.

**Comment by Gerson2102** [comment]
> You forgot the dependencies. Also if you add a parameter please update all the reference (I don't think there'll be any to this specific function, but just in case).
> 
> Rust analyzer may not be working properly to you because this file is behind a feature. If you tell rust-analyzer to enable the `with-debug-utils` feature it should work properly.

I could not found a way to config that :/

**Comment by azteca1998** [comment]
Are you using vscode? (or codium)
If so, just add this to the config:
```json
"rust-analyzer.cargo.allFeatures": true,
```

**Comment by Gerson2102** [comment]
> Are you using vscode? (or codium) If so, just add this to the config:
> 
> ```json
> "rust-analyzer.cargo.allFeatures": true,
> ```

Thanks, now is working.

**Comment by Gerson2102** [comment]
@azteca1998 Hello mate. When you have time, let me know if we are done with this.

**Comment by edg-l** [comment]
There are some more allocas that arent done on the init_block block too, look at the following files:

- poseidon.rs
- ec.rs

**Comment by Gerson2102** [comment]
@azteca1998 @igaray i dont know if someone can help me here, i just tried to do a git rebase main from my feature branch, and i dont know if it went good tbh.

**Comment by Gerson2102** [comment]
This is something that  definetly i dont get it, im getting a bunch of errors locally.

**Pull request closed without merging**
