### PR TITLE
Increase test coverage of Utils module

### PR DESCRIPTION
**Pull request by wugalde19**
This PR addresses the following issue: https://github.com/lambdaclass/cairo_native/issues/483

## Checklist
- [X] Linked to Github Issue
- [X] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by wugalde19** [comment]
@igaray @azteca1998 This PR is ready for review
It took me longer than expected due to the issue of not being able to build nor run the tests on my machine (thanks @azteca1998 again for the help)

I did add a few tests to increase the coverage of the `src/utils.rs` file

I must admit that it was harder than I would have imagined but this was a great challenge and opportunity to learn more about Rust and this project

**NOTE:** I did try to add tests for `cairo_to_sierra` but it is not easy
I did try several approaches starting by sending the program name with a new Path but since those files didn't exist then the tests were panicking
Here's an example of a test that I wrote but did not work because of what I described above

```rust
#[test]
fn test_cairo_to_sierra_cairo_extension_lowercase() {
    let program = PathBuf::from("test.cairo");
    let result = cairo_to_sierra(&program);
    assert!(Arc::strong_count(&result) > 0);
    assert!(Arc::downcast::<Program>(result).is_ok());
}
```

Also tried, mocks, and dependency injection sending the compiler and parser as params but didn't want to change the function signature since it's being used in multiple places), in the end, I decided to get rid of the tests and study the code and tests to come up with a better solution later.


Anyways, please let me know if you have any comments, questions or concerns about my implementation.

Thanks

**Comment by azteca1998** [comment]
Thanks for your contribution. Please fix the clippy and formatting issues so that we can merge it.

**Comment by wugalde19** [comment]
> Thanks for your contribution. Please fix the clippy and formatting issues so that we can merge it.

@azteca1998 I just pushed a commit with the required changes
After formating that file we should be good to go

**Comment by wugalde19** [comment]
@azteca1998 For some reason I did not catch the new Clippy error when I ran the command locally yesterday
I already pushed the fix that is related to the error
https://rust-lang.github.io/rust-clippy/master/index.html#/write_literal

Sorry for the inconvenience

**Review by azteca1998 — APPROVED** [review]

**Review by igaray — APPROVED** [review]

**Pull request merged**
