### PR TITLE
increase `utils` test coverage

### LINKED ISSUE #483: Increase coverage of the utilities module
The coverage of [src/utils.rs](https://app.codecov.io/gh/lambdaclass/cairo_native/blob/main/src%2Futils.rs) could be improved somewhat.

### PR DESCRIPTION
**Pull request by tcoratger**
Should close #483.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by edg-l — DISMISSED** [review]

**Review by juanbono — APPROVED** [review]

**Review by juanbono — DISMISSED** [review]

**Comment by edg-l** [comment]
please fix conflicts

**Comment by tcoratger** [comment]
> please fix conflicts

Done

**Review by juanbono — DISMISSED** [review]

**Review by azteca1998 — APPROVED** [review]

**Comment by juanbono** [comment]
Please fix conflicts @tcoratger

**Comment by tcoratger** [comment]
> Please fix conflicts @tcoratger

Done

**Review by edg-l — APPROVED** [review]

**Review by azteca1998 — APPROVED** [review]

**Review by juanbono — APPROVED** [review]

**Pull request merged**
